Models/CovidGuate.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GenericosLibreria.Estruturas;
using ProyectoFinal_EstDatos.Clases;

namespace ProyectoFinal_EstDatos.Models
{
    public class CovidGuate
    {
        public Hospital HGuatemla = new Hospital() { Nombre = "Hospital de Guatemala"};
        public Hospital HQuetzaltenango = new Hospital() { Nombre = "Hospital de Quetzaltenango" };
        public Hospital HPeten = new Hospital() { Nombre = "Hospital de Petén" };
        public Hospital HEscuintla = new Hospital() { Nombre = "Hospital de Escuintla" };
        public Hospital HZacapa = new Hospital() { Nombre = "Hospital de Zacapa" };
        public TablaHash<Cama> CamasPacientes = new TablaHash<Cama>();
        public Estadisticas EstadisticasGeneral = new Estadisticas();
        public ArbolAVL<Paciente> AVLPacientes = new ArbolAVL<Paciente>();
        public AVLRepetidos<Paciente> AVLNombre = new AVLRepetidos<Paciente>();
        public AVLRepetidos<Paciente> AVLApellido = new AVLRepetidos<Paciente>();
        #region Metodos
        public Hospital AsignarHospital(Paciente AuxPaciente)
        {
            Hospital HAux;
            int NumeroH = AuxPaciente.ObtenerHospital();
            if (NumeroH == 1)
            {
                HGuatemla.Sospechosos.Add(AuxPaciente, AuxPaciente.BuscarPrioridad);
                HAux = HGuatemla;
            }
            else if (NumeroH  == 2)
            {
                HQuetzaltenango.Sospechosos.Add(AuxPaciente, AuxPaciente.BuscarPrioridad);
                HAux = HQuetzaltenango;
            }
            else if (NumeroH == 3)
            {
                HZacapa.Sospechosos.Add(AuxPaciente, AuxPaciente.BuscarPrioridad);
                HAux = HZacapa;
            }
            else if (NumeroH == 4)
            {
                HEscuintla.Sospechosos.Add(AuxPaciente, AuxPaciente.BuscarPrioridad);
                HAux = HEscuintla;
            }
            else 
            {
                HPeten.Sospechosos.Add(AuxPaciente, AuxPaciente.BuscarPrioridad);
                HAux = HPeten;
            }
            return HAux;
        }
       
        #endregion
    }
}

Controllers/CovidGuateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ProyectoFinal_EstDatos.Clases;
using ProyectoFinal_EstDatos.Models;

namespace ProyectoFinal_EstDatos.Controllers
{
    public class CovidGuateController : Controller
    {
        public static CovidGuate Covid19 = new CovidGuate();
        public static Hospital HospitalActual = new Hospital();
        //public static Estadisticas CalcularEstadisticas = new Estadisticas();

        #region Ingrear Pacientes
        // Vista Ingresar Paciente
        public ActionResult IngresarPaciente()
        {
            return View();
        }
        // Guardar Paciente
        [HttpPost]
        public ActionResult GuardarPaciente(IFormCollection collection)
        {
            Paciente AuxPaciente = new Paciente()
            {
                Nombre = collection["Nombre"],
                Apellido = collection["Apellido"],
                Edad = Convert.ToInt32(collection["Edad"]),
                DPI = Convert.ToInt64(collection["DPI"]),
                Departamento = collection["Departamento"],
                Municipio = collection["Municipio"],
                Sintomas = collection["Sintomas"],
                Descripcion = collection["Descripcion"],
                Estado = "Sin Realizar Puebra"
            };
            AuxPaciente.CalcularPrioridad();
            //Asignacion a Hospital Y Mostar Cola Sospechosos
            if (!Covid19.AVLPacientes.ExiteValor(AuxPaciente, AuxPaciente.BuscarDPI))
            {
                HospitalActual = Covid19.AsignarHospital(AuxPaciente);
                Covid19.AVLPacientes.Add(AuxPaciente, AuxPaciente.BuscarDPI);
                Covid19.AVLNombre.Add(AuxPaciente, AuxPaciente.BuscarNombre);
                Covid19.AVLApellido.Add(AuxPaciente, AuxPaciente.BuscarApellido);
                ViewBag.NombreHospital = HospitalActual.Nombre;
                ViewBag.Sospechosos = HospitalActual.Sospechosos.Mostrar();
                ViewBag.Regresar = true;
                Covid19.EstadisticasGeneral.Sospechosos++;
                return View("PacientesSospechosos");
            }
            else
            {
                ViewBag.Error = "¡Paciente Repetido!";
                return View("IngresarPaciente", AuxPaciente);
            }

        }
        public ActionResult RealizarPrueba()
        {
            try
            {
                Paciente AuxPaciente = new Paciente();
            AuxPaciente = HospitalActual.Sospechosos.Delete(AuxPaciente.BuscarPrioridad);
            if (AuxPaciente.ExamenCovid19())
            {
                AuxPaciente.Estado = "Confirmado de Covid-19";
                Covid19.AVLPacientes.Edit(AuxPaciente, AuxPaciente.BuscarDPI);
                Covid19.AVLNombre.Editar(AuxPaciente, AuxPaciente.BuscarNombre, AuxPaciente.BuscarDPI); ;
                Covid19.AVLApellido.Editar(AuxPaciente, AuxPaciente.BuscarApellido, AuxPaciente.BuscarDPI);
                if (HospitalActual.ChequeoIngresar())
                {
                    Cama AuxCama = HospitalActual.Añadir(AuxPaciente);
                    Covid19.CamasPacientes.Añadir(AuxCama, AuxCama.Id);
                    ViewBag.Descripcion = "PACIENTE POSITIVO PARA COVID-19,";
                    ViewBag.Descripcion2 = "Fue Trasladado a Una Cama del " + HospitalActual.Nombre;
                }
                else
                {
                    HospitalActual.EsperaConfrimados.Add(AuxPaciente, AuxPaciente.BuscarPrioridad);
                    ViewBag.Descripcion = "PACIENTE POSITIVO PARA COVID-19";
                    ViewBag.Descripcion2 = "fue trasladado a lista de espera mientras se habilita una cama";
                }
                Covid19.EstadisticasGeneral.Contagiados++;
            }
            else
            {
                //Libre 
                ViewBag.Descripcion = "EL PACIENTE NO TIENE EL VIRUS COVID-19";
                AuxPaciente.Estado = "Libre de Covid-19";
                Covid19.AVLPacientes.Edit(AuxPaciente, AuxPaciente.BuscarDPI);
                Covid19.AVLNombre.Editar(AuxPaciente, AuxPaciente.BuscarNombre, AuxPaciente.BuscarDPI);
                Covid19.AVLApellido.Editar(AuxPaciente, AuxPaciente.BuscarApellido, AuxPaciente.BuscarDPI);
            }
            Covid19.EstadisticasGeneral.PruebasRealizadas++;
            return View(AuxPaciente);
            }
            catch (Exception)
            {
                return View("Index");
            }

        }
        public ActionResult BuscarPaciente()
        {
            ViewBag.Pacientes = Covid19.AVLPacientes.Mostrar();
            return View();
        }
        public ActionResult MostrarEstadisticas()
        {
            try
            {
                double Porcentaje = ((Covid19.EstadisticasGeneral.Contagiados / Covid19.EstadisticasGeneral.PruebasRealizadas) * 100);
                Covid19.EstadisticasGeneral.PorcentajePositivos = Convert.ToString(Porcentaje) + "%";
            }
            catch (Exception)
            {
                Covid19.EstadisticasGeneral.PorcentajePositivos = "0.00%";
            }
            return View(Covid19.EstadisticasGeneral);
        }

        public ActionResult CurarPaciente(int Posicion)
        {
            Cama AuxCama = HospitalActual.Camas[Posicion];
            HospitalActual.Camas[Posicion] = null;
            Covid19.CamasPacientes.Borrar(AuxCama.Id);
            Paciente AuxPaciente = AuxCama.PacienteCama;
            AuxPaciente.Estado = "Recuperado de Covid-19";
            Covid19.AVLPacientes.Edit(AuxPaciente, AuxPaciente.BuscarDPI);
            Covid19.AVLNombre.Editar(AuxPaciente, AuxPaciente.BuscarNombre, AuxPaciente.BuscarDPI);
            Covid19.AVLApellido.Editar(AuxPaciente, AuxPaciente.BuscarApellido, AuxPaciente.BuscarDPI);
            Covid19.EstadisticasGeneral.Recuperados++;
            Paciente EsperaPaciente = new Paciente();
            EsperaPaciente = HospitalActual.EsperaConfrimados.Delete(EsperaPaciente.BuscarPrioridad);
            Cama EsperaCama = HospitalActual.Añadir(EsperaPaciente);
            Covid19.CamasPacientes.Añadir(EsperaCama, EsperaCama.Id);
            return View(AuxPaciente);
        }

        public ActionResult RealizarBusqueda(string Buscar, string Texto)
        {
            if (Texto == null)
            {
                Paciente AuxPaciente = new Paciente();
                if (Buscar == "N")
                {
                    AuxPaciente.Nombre = Texto;
                    ViewBag.Pacientes = Covid19.AVLNombre.Filtrar(AuxPaciente.BuscarNombre, AuxPaciente);
                }
                else if (Buscar == "A")
                {
                    AuxPaciente.Apellido = Texto;
                    ViewBag.Pacientes = Covid19.AVLApellido.Filtrar(AuxPaciente.BuscarApellido, AuxPaciente);
                }
                else
                {
                    try
                    {
                        AuxPaciente.DPI = Convert.ToInt64(Texto);
                        ViewBag.Pacientes = Covid19.AVLPacientes.Get(AuxPaciente, AuxPaciente.BuscarDPI);
                    }
                    catch (Exception)
                    {
                        List<Paciente> ListaError = new List<Paciente>();
                        ViewBag.Pacientes = ListaError;
                        return View("BuscarPaciente");
                    }
                }
            }
            else
            {
                List<Paciente> ListaError = new List<Paciente>();
                ViewBag.Pacientes = ListaError;
            }
            return View("BuscarPaciente");
        }
        #endregion

        #region Hospitales
        public ActionResult Hospitales()
        {
            HospitalActual = new Hospital();
            return View();
        }
        public ActionResult MostrarTablaHash()
            {
            Cama[] ListaCamas = Covid19.CamasPacientes.Mostrar();
            for (int i = 0; i < 50; i++)
                if (ListaCamas[i] == null || ListaCamas[i].PacienteCama == null)
                {
                    ListaCamas[i] = new Cama() { Id = (i + 1), Nombre = "Cama Vacía", DPI = "---", Estado = "Disponible" };
                }
                else
                {
                    ListaCamas[i].Id++;
                }
            ViewBag.Tabla = ListaCamas;
            return View();
        }
        public ActionResult MostrarHospital()
        {
            ViewBag.NombreHospital = HospitalActual.Nombre;
            return View();
        }
        public ActionResult SeleccionarHospital(int id)
        {
            if (id == 1)
                HospitalActual = Covid19.HGuatemla;
            else if (id == 2)
                HospitalActual = Covid19.HQuetzaltenango;
            else if (id == 3)
                HospitalActual = Covid19.HPeten;
            else if (id == 4)
                HospitalActual = Covid19.HEscuintla;
            else
                HospitalActual = Covid19.HZacapa;
            ViewBag.NombreHospital = HospitalActual.Nombre;
            return View("MostrarHospital");
        }
        public ActionResult PacientesSospechosos()
        {
            ViewBag.NombreHospital = HospitalActual.Nombre;
            ViewBag.Sospechosos = HospitalActual.Sospechosos.Mostrar();
            ViewBag.Regresar = false;
            return View();
        }
        public ActionResult ColaConfirmados()
        {
            ViewBag.NombreHospital = HospitalActual.Nombre;
            ViewBag.ColaConfirmados = HospitalActual.EsperaConfrimados.Mostrar();
            return View();
        }
        public ActionResult CamasHospital()
        {
            ViewBag.NombreHospital = HospitalActual.Nombre;
            Cama[] ListaCamas = HospitalActual.Camas;
            Paciente[] ListaPacientes = new Paciente[10];

Views/CovidGuate/BuscarPaciente.cshtml
@model IEnumerable<ProyectoFinal_EstDatos.Clases.Paciente>
@using ProyectoFinal_EstDatos.Clases;
@{
    ViewData["Title"] = "BuscarPaciente";
}
    <body>
        <header class="PacientesSospechos">
            <div class="textos">
                <h1 class="titulo">Buscar Paciente</h1>
                <h3 class="subtitulo">Ingrese los Campos Necesarios</h3>
            </div>
            <div class="sesgoabajo"></div>
        </header>
        <div class="container">
            <nav class="navbar navbar-dark bg-dark">

                <form class="form-inline my-2 my-lg-0" asp-controller="CovidGuate" asp-action="RealizarBusqueda">
                    <div class="btn-group btn-group-toggle" data-toggle="buttons">
                        <label class="btn btn-outline-light active">
                            <input type="radio" name="Buscar" id="Buscar" value="N" autocomplete="off" checked> Nombre
                        </label>
                        <label class="btn btn-outline-light">
                            <input type="radio" name="Buscar" id="Buscar" value="A" autocomplete="off"> Apellido
                        </label>
                        <label class="btn btn-outline-light">
                            <input type="radio" name="Buscar" id="Buscar" value="DPI" autocomplete="off"> DPI/CUI
                        </label>
                    </div>
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="Texto" style="position:absolute; left: 750px;">
                    <button class="btn btn-outline-info my-2 my-sm-0" style="position:absolute; left: 1000px;" type="submit">Buscar</button>
                </form>
            </nav>
            <hr />
            <table class="table table-striped">
                <thead class="thead-dark">
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Nombre)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Apellido)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Edad)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.DPI)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Departamento)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Municipio)
                        </th>
                        <th style="width:auto">
                            Síntomas
                        </th>
                        <th style="width:auto">
                            @Html.DisplayNameFor(model => model.Estado)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Hospital)
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (Paciente item in ViewBag.Pacientes)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Nombre)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Apellido)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Edad)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.DPI)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Departamento)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Municipio)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Sintomas)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Estado)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Hospital)
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <section class="conteneblanco">
            <p>

            </p>
            <a class="btn btn-outline-info btn-lg btn-block" asp-action="Index">Regresar</a>
            <p>

            </p>
        </section>
    </body>

Views/CovidGuate/CamasHospital.cshtml
@model IEnumerable<ProyectoFinal_EstDatos.Clases.Paciente>
@using ProyectoFinal_EstDatos.Clases;
@{
    ViewData["Title"] = "CamasHospital";
}

<body>
    <header class="PacientesSospechos">
        <div class="textos">
            <h1 class="titulo">Camas del Hospital</h1>
            <h3 class="subtitulo">@ViewBag.NombreHospital</h3>
        </div>
        <div class="sesgoabajo"></div>
    </header>
    <div class="container">
        <table class="table table-striped">
            <thead class="thead-dark">
                <tr>
                    <th>
                        No.
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Nombre)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Apellido)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Edad)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.DPI)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Departamento)
                    </th>
                    <th style="width:auto">
                        Síntomas
                    </th>
                    <th style="width:auto">
                        Descripción
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (Paciente item in ViewBag.Confirmados)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Posicion)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Nombre)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Apellido)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Edad)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.DPI)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Departamento)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Sintomas)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Descripcion)
                        </td>
                        <td>
                            @if (item.Nombre == "Cama")
                            {
                                <a class="btn btn-outline-danger btn-lg btn-block"  >Recuperado</a>
                            }
                            else
                            {
                                <a href='@Url.Action("CurarPaciente", "CovidGuate", new { Posicion = (item.Posicion - 1)})' class="btn btn-outline-success btn-lg btn-block">Recuperado</a>
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <div>
            <a class="btn btn-outline-info" asp-action="MostrarHospital">Regresar</a>
        </div>
    </div>
</body>

Views/CovidGuate/ColaConfirmados.cshtml
@model IEnumerable<ProyectoFinal_EstDatos.Clases.Paciente>
@using ProyectoFinal_EstDatos.Clases;

@{
    ViewData["Title"] = "ColaConfirmados";
}
    <body>

        <header class="PacientesSospechos">
            <div class="textos">
                <h1 class="titulo">Lista de Espera de Confirmados</h1>
                <h3 class="subtitulo">@ViewBag.NombreHospital</h3>
            </div>
            <div class="sesgoabajo"></div>
        </header>
        <div class="container">
            <table class="table table-striped">
                <thead class="thead-dark">
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Nombre)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Apellido)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Edad)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.DPI)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Departamento)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Municipio)
                        </th>
                        <th style="width:auto">
                            Síntomas
                        </th>
                        <th style="width:auto">
                            Descripción
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (Paciente item in ViewBag.ColaConfirmados)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Nombre)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Apellido)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Edad)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.DPI)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Departamento)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Municipio)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Sintomas)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Descripcion)
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <div class="sesgoabajo-lista"></div>
        <section class="contenedorlista">
            <p>

            </p>
            <center>
                <a class="btn btn-outline-light btn-block" asp-action="MostrarHospital">Regresar</a>
            </center>
            <p>

            </p>
        </section>
    </body>

Views/CovidGuate/Hospitales.cshtml
@{
    ViewData["Title"] = "Hospitales";
}
    <body>
        <header class="Hospitales">
            <div class="textos">
                <h1 class="titulo">Hospitales</h1>
                <h3 class="subtitulo"> Red De Hospitales Covid-19 en Guatemala</h3>
            </div>
            <div class="sesgoabajo"></div>
        </header>

        <section class="cards contenedor">
            <h2 style="text-align:center">Hospitales</h2>
            <hr />
            <div class="content-cards">
                <article class="card">
                    <img src="~/Imagenes/Guatemala.jpg" alt="" width="260">
                    <a href='@Url.Action("SeleccionarHospital","CovidGuate", new { id = 1})' class="btn btn-outline-dark btn-lg btn-block">Hospital De Guatemala</a>
                </article>
                <article class="card">
                    <img src="~/Imagenes/Region2.jpg" alt="" width="260">
                    <a href='@Url.Action("SeleccionarHospital","CovidGuate", new { id = 2})' class="btn btn-outline-info btn-lg btn-block">Hospital De Quetzaltenango</a>
                </article>
                <article class="card">
                    <img src="~/Imagenes/Region3.jpg" alt="" width="260">
                    <a href='@Url.Action("SeleccionarHospital","CovidGuate", new { id = 3})' class="btn btn-outline-warning btn-lg btn-block">Hospital De Petén</a>
                </article>
            </div>
            <hr />
            <div class="content-cards">
                <article class="card">
                    <img src="~/Imagenes/Region4.jpg" alt="" width="260">
                    <a href='@Url.Action("SeleccionarHospital","CovidGuate", new { id = 4})' class="btn btn-outline-primary btn-lg btn-block">Hospital De Escuintla</a>
                </article>
                <article class="card">
                    <img src="~/Imagenes/Region5.jpg" alt="" width="260">
                    <a href='@Url.Action("SeleccionarHospital","CovidGuate", new { id = 5})' class="btn btn-outline-success btn-lg btn-block">Hospital De Zacapa</a>
                </article>
                <article class="card">
                    <img src="~/Imagenes/Back.png" alt="" width="250">
                    <a class="btn btn-outline-info btn-lg btn-block" asp-action="Index">Regresar</a>
                </article>
            </div>
        </section>
        <h2 class="titulo-final"></h2>
        <div class="sesgoabajo-hospitales"></div>
    </body>

Views/CovidGuate/MostrarTablaHash.cshtml
@model IEnumerable<ProyectoFinal_EstDatos.Clases.Cama>
@using ProyectoFinal_EstDatos.Clases;
@{
    ViewData["Title"] = "MostrarTablaHash";
}

    <body>
        <header class="PacientesSospechos">
            <div class="textos">
                <h1 class="titulo">Pacientes Antendidos Por Camas</h1>
                <h3 class="subtitulo">Tabla de Pacientes</h3>
            </div>
            <div class="sesgoabajo"></div>
        </header>
        <div class="container">
            <hr />
            <nav class="navbar navbar-dark bg-dark">

                <form class="form-inline my-2 my-lg-0" asp-controller="CovidGuate" asp-action="BuscarHash">
                    <div class="btn-group btn-group-toggle" data-toggle="buttons">
                        <label class="btn btn-outline-light active">
                            <input type="radio" name="Buscar" id="Buscar" value="ID" autocomplete="off" checked> ID
                        </label>
                        <label class="btn btn-outline-light">
                            <input type="radio" name="Buscar" id="Buscar" value="1" autocomplete="off"> Guatemala
                        </label>
                        <label class="btn btn-outline-light">
                            <input type="radio" name="Buscar" id="Buscar" value="2" autocomplete="off"> Quetzaltenango
                        </label>
                        <label class="btn btn-outline-light">
                            <input type="radio" name="Buscar" id="Buscar" value="3" autocomplete="off"> Zacapa
                        </label>
                        <label class="btn btn-outline-light">
                            <input type="radio" name="Buscar" id="Buscar" value="4" autocomplete="off"> Escuintla 
                        </label>
                        <label class="btn btn-outline-light">
                            <input type="radio" name="Buscar" id="Buscar" value="5" autocomplete="off"> Petén 
                        </label>
                    </div>
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="Texto" style="position:absolute; left: 750px;">
                    <button class="btn btn-outline-info my-2 my-sm-0" style="position:absolute; left: 1000px;" type="submit">Buscar</button>
                </form>
            </nav>
            <hr />
            <table class="table table-striped">
                <thead class="thead-dark">
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Id)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Estado)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Nombre)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.DPI)
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (Cama item in ViewBag.Tabla)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Id)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Estado)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Nombre)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.DPI)
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <section class="contenedorlista">
            <p>

            </p>
            <center>
                <a class="btn btn-outline-light btn-block" asp-action="Index">Regresar</a>
            </center>
            <p>

            </p>
        </section>
    </body>